spring.application.name=driver-service
server.port=8082

# ==================================
# Mutual TLS handshake connection
# ==================================
server.ssl.enabled=true
server.ssl.key-store=file:certs/driver/driver-service-keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${DRIVER_SERVER_KEYSTORE_PASSWORD}
server.ssl.key-alias=driver-service

server.ssl.trust-store=file:certs/driver/driver-service-truststore.p12
server.ssl.trust-store-type=PKCS12
server.ssl.trust-store-password=${DRIVER_TRUSTSTORE_PASSWORD}

server.ssl.client-auth=need

# ==========================
# Datasource connection
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=90000

spring.jpa.show-sql=true

# =================================================
# OAuth2 validating jwt token against Cognito
# =================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_hLZj5IXWc

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security.oauth2.client=TRACE
logging.level.org.springframework.security.oauth2.core=TRACE

# ================
# Redis cache
# ================
spring.data.redis.host=redis-cache
spring.data.redis.port=6379
spring.cache.redis.time-to-live=10m

# ======================================
# Eureka unregistered on locally
# ======================================
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false