INSERT INTO driver (name, team) VALUES
('Liam Carter', 'Mercedes'),
('Noah Bennett', 'Mercedes'),
('Ethan Mitchell', 'Red Bull'),
('Lucas Anderson', 'Red Bull'),
('Oliver Parker', 'Ferrari'),
('Henry Collins', 'Ferrari'),
('James Cooper', 'McLaren'),
('William Turner', 'McLaren'),
('Benjamin Foster', 'Aston Martin'),
('Samuel Brooks', 'Aston Martin'),
('Daniel Morgan', 'Alpine'),
('Jack Richardson', 'Alpine'),
('Alexander Ward', 'Williams'),
('Matthew Hughes', 'Williams'),
('Sebastian Price', 'RB'),
('Jacob Murray', 'RB'),
('Michael Kelly', 'Sauber'),
('David Peterson', 'Sauber'),
('Joseph Reed', 'Haas'),
('Thomas Bailey', 'Haas'),
('Christopher Bell', 'Mercedes'),
('Andrew Murphy', 'Mercedes'),
('Joshua Cooper', 'Red Bull'),
('Ryan Richardson', 'Red Bull'),
('Nathan Cox', 'Ferrari'),
('Dylan Howard', 'Ferrari'),
('Caleb Ward', 'McLaren'),
('Isaac Torres', 'McLaren'),
('Gabriel Flores', 'Aston Martin'),
('Anthony Rivera', 'Aston Martin'),
('Julian Bennett', 'Alpine'),
('Aaron Phillips', 'Alpine'),
('Connor Campbell', 'Williams'),
('Adrian Parker', 'Williams'),
('Evan Evans', 'RB'),
('Brandon Edwards', 'RB'),
('Cameron Stewart', 'Sauber'),
('Jason Sanchez', 'Sauber'),
('Tyler Morris', 'Haas'),
('Jordan Rogers', 'Haas'),
('Logan Peterson', 'Mercedes'),
('Mason Cook', 'Mercedes'),
('Hunter Bailey', 'Red Bull'),
('Owen Bell', 'Red Bull'),
('Wyatt Murphy', 'Ferrari'),
('Luke Cooper', 'Ferrari'),
('Charles Richardson', 'McLaren'),
('Isaiah Cox', 'McLaren'),
('Asher Howard', 'Aston Martin'),
('Leo Flores', 'Aston Martin'),
('Grayson Rivera', 'Alpine'),
('Lincoln Phillips', 'Alpine'),
('Hudson Campbell', 'Williams'),
('Mateo Stewart', 'Williams'),
('Ezra Sanchez', 'RB'),
('Julian Morris', 'RB'),
('Nolan Rogers', 'Sauber'),
('Archer Cook', 'Sauber'),
('Miles Evans', 'Haas'),
('Colton Edwards', 'Haas'),
('Finn Morgan', 'Mercedes'),
('Theo Hughes', 'Mercedes'),
('Riley Reed', 'Red Bull'),
('Blake Bailey', 'Red Bull'),
('Kai Torres', 'Ferrari'),
('Cole Flores', 'Ferrari'),
('Jace Rivera', 'McLaren'),
('Axel Phillips', 'McLaren'),
('Silas Campbell', 'Aston Martin'),
('Dean Stewart', 'Aston Martin'),
('Max Sanchez', 'Alpine'),
('Wesley Morris', 'Alpine'),
('Grant Rogers', 'Williams'),
('Tristan Cook', 'Williams'),
('Eric Evans', 'RB'),
('Marcus Edwards', 'RB'),
('Victor Morgan', 'Sauber'),
('Dominic Hughes', 'Sauber'),
('Patrick Reed', 'Haas'),
('Steven Bailey', 'Haas'),
('Trevor Torres', 'Mercedes'),
('Cody Flores', 'Mercedes'),
('Blake Rivera', 'Red Bull'),
('Derek Phillips', 'Red Bull'),
('Shane Campbell', 'Ferrari'),
('Marcus Stewart', 'Ferrari'),
('Colin Sanchez', 'McLaren'),
('Warren Morris', 'McLaren'),
('Gavin Rogers', 'Aston Martin'),
('Troy Cook', 'Aston Martin'),
('Neil Evans', 'Alpine'),
('Scott Edwards', 'Alpine'),
('Brendan Morgan', 'Williams'),
('Kieran Hughes', 'Williams'),
('Damian Reed', 'RB'),
('Marcus Bailey', 'RB'),
('Jonah Torres', 'Sauber'),
('Felix Flores', 'Sauber'),
('Roman Rivera', 'Haas'),
('Max Verstappen', 'Redbull Racing'),
('Sergio Perez', 'Redbull Racing'),
('George Russel', 'Mercedes-AMG'),
('Kimi Attonelli', 'Mercedes-AMG'),
('Nico Rosberg', 'Mercedes-AMG'),
('Charles Leclerc', 'Scuderia Ferrari'),
('Lewis Hamilton', 'Scuderia Ferrari');