name: ECS Driver Service Deployment

on:
  # Triggered by git push event at main branch
  push:
    branches:
      - main

  # Supported trigger the deployment manually
  workflow_dispatch:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: capstone/driver-service
  ECS_CLUSTER: capstone-ecs-cluster
  ECS_SERVICE: driver-service
  ECS_TASK_DEFINITION: driver-service-fargate-td
  REGISTRY: 249899229305.dkr.ecr.ap-southeast-1.amazonaws.com

# ECS Driver Service Deployment Jobs
jobs:
  ecs-driver-service-deployment:

    # Generally start with x86/AMD64 GitHub runner
    runs-on: ubuntu-latest

    # Required manually approval
    environment:
      name: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::249899229305:role/github-actions-driver-deployment-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Allows x86 Github runner to execute ARM64 binaries
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Uses: Pre-built GitHub Action package
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Run: executes raw AWS cli - NO Github action pre-built support on describe task definition operation
      - name: Get current ECS task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition "$ECS_TASK_DEFINITION" \
            --query 'taskDefinition' \
            --output json > task-definition.json

      - name: Render a new task definition embedded new image tagged
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: render-task-definition
        with:
          task-definition: task-definition.json
          container-name: driver-service
          image: ${{ env.REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          wait-max-delay-seconds: 400